//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper.Come {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class SystemHelperInfo : global::System.Configuration.ApplicationSettingsBase {
        
        private static SystemHelperInfo defaultInstance = ((SystemHelperInfo)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SystemHelperInfo())));
        
        public static SystemHelperInfo Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System.CurrentDayTime")]
        public string CurrentDayTime {
            get {
                return ((string)(this["CurrentDayTime"]));
            }
            set {
                this["CurrentDayTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System.DefaultNameSpace")]
        public string DefaultNameSpace {
            get {
                return ((string)(this["DefaultNameSpace"]));
            }
            set {
                this["DefaultNameSpace"] = value;
            }
        }
    }
}
